### ISSUE TITLE
Небольшое улучшение Makefile'а

### ISSUE THREAD

**Issue by DarkSeriusCode** [etar125/e125#1]
У тебя в `README` указано, что необходимо создать директорию `bin`, однако в `make` есть способ делать это автоматически. После цели `default` добавь `$(shell mkdir -p bin)`. PR создавать не стал, так как изменение ну уж очень маленькое, поэтому написал тут.

**Comment by etar125** [comment]
Спасибо, добавил.

**Comment by etar125** [comment]
Хз, думаю
